dream-faster/fold

src/drift/loop/fit_transformations.py
src/drift/loop/inference.py
src/drift/loop/train.py
src/drift/utils/splitters.py
tests/test_baseline_model.py

new interface:
```
def __init__(
self,
train_window_size: int,
step: int,
start: int = 0,
end: Optional[int] = None,
) -> None:
```

feature(Splitters): using a better interface

---

src/drift/loop/inference.py
tests/test_transformation.py

fix(Transformations): inference wasn't working & added tests

---

src/drift/models/sklearn.py

fix(Models): wrap model output into pd.Series

---

src/drift/loop/convenience.py
src/drift/loop/inference.py
src/drift/loop/train.py
src/drift/models/base.py
src/drift/models/ensemble.py
src/drift/transformations/__init__.py
src/drift/transformations/base.py
src/drift/transformations/columns.py
src/drift/transformations/concat.py
src/drift/transformations/identity.py
tests/test_transformations.py

feature(Composite): allow nested pipelines

---

example.py
src/drift/loop/convenience.py
src/drift/loop/train.py
src/drift/models/ensemble.py
src/drift/transformations/base.py
src/drift/transformations/columns.py
src/drift/transformations/concat.py
src/drift/transformations/sklearn.py
src/drift/transformations/univariate.py
src/drift/utils/list.py
src/drift/utils/pandas.py
tests/test_transformations.py

fix(Loop): deepcopying done correctly, fixed Concat swapping column order if there are duplicates

---

example.py
src/drift/loop/convenience.py
src/drift/transformations/__init__.py
src/drift/transformations/univariate.py
tests/test_loop.py
tests/test_transformations.py

chore(Project): remove unused imports

---

src/drift/models/baseline.py
src/drift/models/ensemble.py

fix(Models): Ensemble was getting the mean on the wrong axis

---

src/drift/loop/convenience.py
src/drift/loop/inference.py
src/drift/loop/train.py
src/drift/models/base.py
src/drift/models/ensemble.py
src/drift/transformations/__init__.py
src/drift/transformations/base.py
src/drift/transformations/columns.py
src/drift/transformations/sklearn.py
src/drift/transformations/target.py
src/drift/utils/list.py
tests/test_transformations.py

feature(Transformations): added TransformTarget() Composite transformation

---

src/drift/loop/convenience.py
src/drift/loop/inference.py
src/drift/loop/train.py
src/drift/models/__init__.py
src/drift/models/ensemble.py
src/drift/transformations/__init__.py
src/drift/transformations/base.py
src/drift/transformations/columns.py
tests/test_ensembles.py
tests/test_transformations.py

feature(Transformations): added PerColumnEnsemble & PerColumnTransformation

---

.github/workflows/ci-cd.yaml

fix(CI): environment specified

---

.github/workflows/ci-cd.yaml
pyproject.toml

fix(CI): added pytest-cov

---

README.md

chore(Docs): updated README with codecov badge

---

src/drift/loop/convenience.py
src/drift/loop/train.py
src/drift/models/__init__.py
src/drift/models/baseline.py
src/drift/models/ensemble.py
src/drift/models/sklearn.py
src/drift/transformations/__init__.py
src/drift/transformations/base.py
src/drift/transformations/columns.py
src/drift/transformations/common.py
src/drift/transformations/concat.py
src/drift/transformations/target.py
src/drift/utils/list.py
src/drift/utils/tests.py
tests/test_ensembles.py
tests/test_sklearn.py
tests/test_transformations.py

feature(Models): propagate probabilities along with preditions for classifers

---

src/drift/models/ensemble.py
src/drift/utils/tests.py
tests/test_ensembles.py

feature(Tests): added tests for Ensembling probabilities

---

src/drift/models/ensemble.py

fix(Ensemble): match class columns exactly

---

src/drift/loop/infer.py
src/drift/loop/train.py
src/drift/models/__init__.py
src/drift/models/base.py
src/drift/models/baseline.py
src/drift/models/dummy.py
src/drift/models/ensemble.py
src/drift/models/metalabeling.py
src/drift/models/sklearn.py
src/drift/transformations/base.py
src/drift/transformations/columns.py
src/drift/transformations/concat.py
src/drift/transformations/target.py
src/drift/utils/checks.py
tests/test_loop.py
tests/test_metalabelling.py

feature(Composite): added MetaLabeling, Composite.Properties, ability to add secondary transformations in Composite

---

src/drift/splitters.py
src/drift/transformations/target.py
tests/test_splitters.py

feature(Splitters): added optional embargo between train/test sets & tests for all Splitters

---

src/drift/loop/infer.py
src/drift/loop/train.py
src/drift/models/__init__.py
src/drift/models/ensemble.py
src/drift/transformations/columns.py
src/drift/transformations/common.py
src/drift/utils/checks.py
tests/test_skipna.py

feature(Composite): added SkipNA class, and tests

---

src/drift/loop/backend/ray.py
src/drift/loop/train.py

feature(Loop): added Backend option utilizing ray

---

pyproject.toml
src/drift/loop/infer.py
src/drift/loop/train.py
src/drift/models/baseline.py
src/drift/transformations/__init__.py
src/drift/transformations/sampling.py
src/drift/utils/tests.py
tests/test_sampling.py

feature(Transformation): added Sampling class, wrapping any imblearn-learn sampler

---

docs/design/composite.md
src/drift/loop/infer.py
src/drift/loop/train.py
src/drift/models/ensemble.py
src/drift/models/metalabeling.py
src/drift/transformations/base.py
src/drift/transformations/columns.py
src/drift/transformations/common.py
src/drift/transformations/target.py
src/drift/utils/list.py
tests/test_metalabelling.py
tests/test_skipna.py
tests/test_transformations.py

refactor(Composite): TransformTarget is now a `Composite`

---

.github/workflows/ci-cd.yaml
src/drift/loop/backtest.py
src/drift/loop/train.py

feature(CI): run the tests on every combination of OSes and python versions

---

README.md

fix(Docs): tests badge

---

README.md

feature(Docs): added docs badge

---

README.md
src/fold/loop/convenience.py
src/fold/models/sklearn.py
tests/test_sklearn.py

feature(Models): support SKLearn Pipeline objects as well

---

README.md
docs/continuous-validation.md
docs/deployment.md
docs/models.md
docs/reference.md
docs/speed.md
docs/splitters.md

feature(Docs): added a couple of new pages

---

README.md
docs/reference.md

fix(Docs): updated

---

.github/workflows/docs.yaml

feature(CI): build docs even when on a branch, but don't deploy

---

src/fold/loop/backtest.py
src/fold/loop/common.py
src/fold/loop/infer.py
src/fold/loop/train.py
src/fold/models/base.py
src/fold/models/baseline.py
src/fold/models/dummy.py
src/fold/models/random.py
src/fold/models/sklearn.py
src/fold/splitters.py
src/fold/transformations/base.py
src/fold/transformations/breakpoint.py
src/fold/transformations/columns.py
src/fold/transformations/function.py
src/fold/transformations/identity.py
src/fold/transformations/sampling.py
src/fold/transformations/sklearn.py
src/fold/transformations/test.py
src/fold/transformations/update.py
tests/test_ensembles.py

refactor(Loop): added `.update()` method, which we now call in the inner loop when `requires_continuous_updates == True`

---

src/fold/splitters.py

fix(Splitters): allow window_size of `1`

---

src/fold/utils/tests.py
tests/test_baselines.py
tests/test_deployment.py
tests/test_ensembles.py
tests/test_loop.py
tests/test_metalabelling.py
tests/test_model.py
tests/test_sampling.py
tests/test_skipna.py
tests/test_sklearn.py
tests/test_splitters.py
tests/test_transformations.py

feature(Utils): added `generate_monotonous_data()`

---

README.md

feature(Docs): unifying the different sections

---

README.md
docs/design.md
src/fold/loop/backend/ray.py
src/fold/loop/backend/sequential.py
src/fold/loop/backtest.py
src/fold/loop/common.py
src/fold/loop/train.py
src/fold/models/baseline.py
src/fold/splitters.py
src/fold/transformations/base.py
src/fold/transformations/update.py
tests/test_baselines.py
tests/test_ensembles.py
tests/test_loop.py
tests/test_metalabelling.py
tests/test_model.py
tests/test_sampling.py
tests/test_skipna.py
tests/test_sklearn.py
tests/test_splitters.py
tests/test_transformations.py

refactor(Project): renamed `Split` class to `Fold`, `requires_continuous_updates` to `Transformation.Properties.Mode.online`

---

src/fold/models/__init__.py
src/fold/models/dummy.py
src/fold/models/hybrid.py
tests/test_hybrid.py

feature(Models): added Hybrid Composite

---

src/fold/transformations/lags.py
tests/test_transformations.py

feature(Transformation): added `AddLagsY` class

---

src/fold/loop/common.py

fix(Loop): inner loop should return a DataFrame as well, no matter what

---

src/fold/models/base.py

fix(Models): Always use the same model name for predictions.

---

README.md
pyproject.toml
src/fold/loop/backend/ray.py
src/fold/loop/backend/sequential.py
src/fold/loop/backtest.py
src/fold/loop/common.py
src/fold/loop/infer.py
src/fold/loop/train.py
src/fold/loop/types.py

feature(Loop): parallelize training of child transformations

---

src/fold/transformations/concat.py
tests/test_ensembles.py

feature(Composite): Added pipeline to make it convienent to understand sequential models.

---

src/fold/loop/train.py
src/fold/loop/types.py
src/fold/transformations/lags.py
src/fold/utils/list.py
tests/test_transformations.py

feature(Transformation): added `AddLagsX`

---

src/fold/transformations/__init__.py
src/fold/transformations/date.py
tests/test_transformations.py

feature(Transformation): added `AddDateTimeFeatures` class

---

src/fold/loop/common.py
src/fold/models/__init__.py
src/fold/models/baseline.py
src/fold/transformations/base.py
src/fold/transformations/function.py
src/fold/transformations/lags.py
src/fold/transformations/update.py
src/fold/utils/tests.py
tests/test_baselines.py
tests/test_deployment.py
tests/test_loop.py
tests/test_splitters.py
tests/test_transformations.py

fix(Models): NaiveSeasonal should return the value from previous season, renamed `memory` to `memory_size`, added RollingMean, drop `Baseline` prefix

---

src/fold/loop/backend/ray.py
src/fold/loop/backend/sequential.py
src/fold/loop/backtest.py
src/fold/loop/train.py

feature(Loop): silent mode to surpress tqdm logs

---

src/fold/transformations/window.py
tests/test_transformations.py

feature(Transformations): added `AddWindowFeatures` class

---

.github/workflows/publish.yaml

feature(CI): added publish workflow

---

src/fold/transformations/__init__.py
src/fold/utils/tests.py

Closes https://github.com/dream-faster/fold/pull/176

fix(Tests): generate_monotonous_data() is returning the correct length sequence, export Difference

---

.flake8
examples/ensemble_vs_single.py
examples/utils.py
pyproject.toml

feature(Examples): Ensemble comparison with Energy data.

---

src/fold/loop/encase.py
src/fold/models/baseline.py

fix(Loop): don't expose "mutate"

---

README.md
examples/ensemble_vs_single.py
examples/utils.py

… functions for data preprocessing.
Closes #

feature(Docs): Updated example with easier data loading. Created util functions for data preprocessing.

---

src/fold/utils/dataset.py

fix(Utils): deduplication strategy should be passed as value

---

docs/examples/date.py
docs/examples/ensembling.py
docs/examples/preprocess.py
src/fold/transformations/holidays.py
src/fold/transformations/lags.py

feature(Docs): updated examples

---

src/fold/transformations/columns.py
src/fold/transformations/lags.py
src/fold/transformations/window.py
src/fold/utils/checks.py
tests/test_transformations.py

feature(Transformations): `AddLagX` can now receive `('all', integer)` to apply lags for all columns

---

src/fold/transformations/holidays.py

fix(Transformation): Holiday features was referring to an unwrapped list and gave an error.

---

src/fold/loop/common.py
src/fold/models/baseline.py
src/fold/models/dummy.py
src/fold/models/random.py
src/fold/models/sklearn.py
src/fold/transformations/base.py
src/fold/transformations/columns.py
src/fold/transformations/date.py
src/fold/transformations/dev.py
src/fold/transformations/difference.py
src/fold/transformations/function.py
src/fold/transformations/holidays.py
src/fold/transformations/lags.py
src/fold/transformations/sklearn.py
src/fold/transformations/update.py
src/fold/transformations/window.py
src/fold/utils/tests.py
tests/test_loop.py
tests/test_loop_train_methods.py

feature(Transformation): added Transformation.Properties.requires_X and checks

---

src/fold/loop/checks.py
src/fold/loop/training.py
src/fold/splitters.py
src/fold/utils/checks.py
src/fold/utils/pandas.py
tests/test_loop.py
tests/test_utils.py

fix(Utils): properly truncate initial NaNs in X

---

src/fold/loop/backend/sequential.py
src/fold/loop/backtesting.py

chore(Loop): `tqdm` is now imported from `tqdm.auto` to support colab and jupyter notebooks

---

docs/api/composites.md
docs/api/transformations.md
src/fold/composites/concat.py
src/fold/composites/ensemble.py
src/fold/composites/hybrid.py
src/fold/composites/metalabeling.py
src/fold/composites/sample.py
src/fold/transformations/columns.py
src/fold/transformations/date.py
src/fold/transformations/difference.py
src/fold/transformations/math.py

feature(Docs): populated some docstrings with examples

---

docs/api/base.md
docs/api/loop.md
docs/api/reference.md
mkdocs.yml
src/fold/composites/concat.py
src/fold/composites/hybrid.py
src/fold/composites/metalabeling.py
src/fold/composites/sample.py
src/fold/composites/target.py
src/fold/loop/encase.py
src/fold/loop/training.py

I also corrected minor outdated type annotations and allowed backend to be a string.
Closes #

feature(Docs): Added more docstrings and restructured `api` page to have seperate types and main loops.

---

src/fold/base.py
src/fold/composites/hybrid.py
src/fold/composites/metalabeling.py
src/fold/composites/sample.py
src/fold/loop/convenience.py
src/fold/loop/encase.py
src/fold/loop/training.py
src/fold/models/__init__.py
src/fold/models/sklearn.py
src/fold/transformations/__init__.py
src/fold/transformations/sklearn.py

refactor(Loop): removed BlocksOrWrappable type

---

src/fold/composites/columns.py
src/fold/loop/backtesting.py
src/fold/loop/encase.py
src/fold/loop/training.py
src/fold/loop/types.py
src/fold/transformations/date.py

feature(Docs): added docstrings to all public functions in `loop`

---

docs/api/base.md
src/fold/models/__init__.py
src/fold/models/baseline.py
src/fold/models/dummy.py
src/fold/models/random.py

feature(Docs): added docstrings and examples to all Models

---

README.md

fix(Docs): README should not depend on krisi

---

src/fold/models/base.py
src/fold/models/baseline.py

feature(Models): added `TimeSeriesModel` base class

---

README.md
docs/walkthroughs/benchmarking_sktime_fold.md
docs/walkthroughs/core_walkthrough.md

feature(Docs): Updated the example links and the walkthrough colab links.

---

src/fold/base.py
src/fold/loop/common.py
src/fold/loop/memory.py
src/fold/models/base.py
src/fold/models/baseline.py
src/fold/models/sklearn.py
src/fold/transformations/dev.py
src/fold/transformations/difference.py
src/fold/transformations/math.py
src/fold/transformations/sklearn.py
src/fold/transformations/update.py
tests/unit/test_loop_train_methods.py
tests/unit/test_memory.py
tests/unit/test_transformations.py

fix(Loop): memory now only adds maximum `memory_size` past values, `y` is now non-optional during `fit()` and `update()`

---

LICENSE
README.md

feature(Licence): Updated Licence.

---

README.md

fix(Docs): updated Licence&Usage section

---

pyproject.toml
tests/integration/test_integration.py

fix(Tests): ability to load `fold` as a package, make `ray` detect if module can't be loaded

---

src/fold/models/baseline.py
tests/unit/test_model.py

fix(Models): `Naive` model's speed regression is resolved

---

.github/workflows/bump-version.yaml

feature(CI): added bump-version workflow

---

src/fold/models/base.py
tests/integration/test_integration.py

fix(Models): TimeSeriesModel base class is slicing `X` correctly

---

README.md

fix(Docs): added one more feature to the list in README

---

src/fold/base.py
src/fold/loop/inference.py
src/fold/loop/training.py
src/fold/loop/update.py
tests/unit/test_deployment.py

feature(Loop): deployment functions added (with tests)

---

README.md

chore(Docs): updated project title to include "Time Series"

---

docs/product/pricing.md

chore(Docs): Pricing table changed.

---

src/fold/base.py
src/fold/composites/metalabeling.py
src/fold/composites/residual.py
src/fold/composites/target.py
src/fold/loop/common.py
src/fold/transformations/dev.py
src/fold/transformations/difference.py
src/fold/transformations/math.py
src/fold/transformations/sklearn.py
tests/unit/test_difference.py
tests/unit/test_transform_target.py
tests/unit/test_transformations.py

fix(Tests): Difference works both in- and out-of-sample, tests now cover all cases 

---

src/fold/transformations/__init__.py
src/fold/transformations/difference.py
tests/unit/test_difference.py

feature(Transformations): added `TakeReturns` class

---

README.md

fix(Docs): updated release blog post title in README

---

README.md

fix(Docs): updated Licence section

---

src/fold/utils/checks.py
tests/unit/test_difference.py
tests/unit/test_transform_target.py

fix(Utils): `get_prediction_column()` should always return a pd.Series

---

src/fold/base.py
src/fold/composites/optimize.py
src/fold/loop/backend/ray.py
src/fold/loop/backend/sequential.py
src/fold/loop/common.py
src/fold/models/sklearn.py
src/fold/transformations/lags.py
src/fold/transformations/math.py
src/fold/transformations/sklearn.py
tests/unit/test_optimizer.py
tests/unit/tuneable.py

feature(Composite): Grid Search Optimizer.

---

src/fold/base.py
src/fold/composites/optimize.py
src/fold/models/sklearn.py
src/fold/transformations/lags.py
src/fold/transformations/math.py
src/fold/transformations/sklearn.py
src/fold/utils/tests.py
tests/unit/test_sklearn.py

refactor(Tunable): renamed `set_params()` to `clone_with_params()` and added default implementation

---

src/fold/transformations/columns.py
src/fold/transformations/date.py
src/fold/transformations/difference.py
src/fold/transformations/holidays.py
src/fold/transformations/window.py
src/fold/utils/tests.py
tests/unit/test_difference.py
tests/unit/test_transformations.py
tests/unit/test_transformations_datetime.py

feature(Transformations): made all of them `Tunable`

---

.github/workflows/tests.yaml
pyproject.toml
src/fold/composites/optimize.py
src/fold/loop/common.py
tests/integration/test_gridsearch.py

fix(Optimizer): trim initial NaNs from in-sample results

---

src/fold/base.py
src/fold/loop/common.py
src/fold/models/base.py
src/fold/transformations/columns.py
src/fold/transformations/date.py
src/fold/transformations/dev.py
src/fold/transformations/difference.py
src/fold/transformations/function.py
src/fold/transformations/holidays.py
src/fold/transformations/lags.py
src/fold/transformations/math.py
src/fold/transformations/sklearn.py
src/fold/transformations/update.py
src/fold/transformations/window.py
src/fold/utils/dataframe.py
src/fold/utils/list.py
tests/unit/test_artifacts.py
tests/unit/test_difference.py
tests/unit/test_transformations.py

Revert "feature(Transformations): `.transform()` now returns an optional Artifact"

---

src/fold/composites/common.py
src/fold/utils/list.py
tests/unit/test_utils.py

feature(Utils): added traverse_pipeline function

---

src/fold/base.py
src/fold/loop/checks.py
src/fold/loop/common.py
src/fold/loop/memory.py
src/fold/utils/dataframe.py
src/fold/utils/functional.py
src/fold/utils/trim.py
tests/integration/test_integration.py
tests/unit/test_memory.py
tests/unit/test_utils.py

fix(Loop): also store past `sample_weights` in Transformation's State

---

pyproject.toml
src/fold/loop/backend/__init__.py
src/fold/loop/backend/pathos.py
src/fold/loop/backend/process.py
src/fold/loop/backend/thread.py
src/fold/loop/types.py
src/fold/transformations/window.py
tests/integration/test_integration.py

feature(Loop): added new `pathos`, `thread` backends

---

src/fold/base.py
src/fold/utils/tests.py
tests/unit/test_hpo.py
tests/unit/test_utils.py

fix(Tunable): `id` should be unique per instance.

---

pyproject.toml
src/fold/loop/encase.py
src/fold/utils/checks.py
tests/unit/test_checks.py

chore(Dependency): Updated `krisi` to support probabilities, tailored `fold` to pass it to `krisi` & wrote unit tests for `utils.checks`.

---

pyproject.toml
src/fold/transformations/difference.py
src/fold/transformations/holidays.py
tests/unit/test_difference.py

feature(Transformation): added `MakeStationary` class

---

src/fold/splitters.py
tests/unit/test_splitters.py

feature(Splitters): added ability to merge last Fold with the previous one if test_window is too small

---

src/fold/models/base.py
src/fold/utils/checks.py
tests/unit/test_utils.py

fix(Models): should output stable order of probabilities columns

---

src/fold/composites/concat.py
src/fold/loop/types.py
src/fold/transformations/date.py
src/fold/transformations/difference.py
src/fold/transformations/holidays.py
src/fold/transformations/window.py
src/fold/utils/dataset.py
src/fold/utils/enums.py

feature(Utils): added ParsableEnum base class

---

src/fold/base/classes.py
src/fold/composites/columns.py
src/fold/composites/common.py
src/fold/composites/concat.py
src/fold/composites/ensemble.py
src/fold/composites/metalabeling.py
src/fold/composites/optimize.py
src/fold/composites/residual.py
src/fold/composites/sample.py
src/fold/composites/select.py
src/fold/composites/target.py
src/fold/events/__init__.py
src/fold/loop/wrap.py
src/fold/models/dummy.py
src/fold/models/sklearn.py
src/fold/transformations/columns.py
src/fold/transformations/date.py
src/fold/transformations/difference.py
src/fold/transformations/holidays.py
src/fold/transformations/lags.py
src/fold/transformations/math.py
src/fold/transformations/sklearn.py
src/fold/transformations/window.py
tests/unit/test_hpo.py
tests/unit/test_sklearn.py

feature(Composites): SelectBest now uses name instead of index

---

.github/workflows/tests.yaml
README.md
pyproject.toml

chore(Dependencies): remove python 3.7 support

---

src/fold/base/classes.py
src/fold/composites/optimize.py
src/fold/composites/select.py
src/fold/composites/utils.py
src/fold/loop/common.py
tests/unit/test_hpo.py

feature(Optimizer): changed get_candidates() api so candidate evaluation only steps when an array with length of zero is returned

---

src/fold/base/classes.py
src/fold/composites/optimize.py
src/fold/loop/common.py

feature(Optimizer): added new parameters to the internal API

---

src/fold/transformations/sklearn.py

feature(Wrapper): If we save the `init_args` and the `model_class` we can use wrappers within other objects/composites.

---

pyproject.toml
src/fold/composites/utils.py

feature(Utils): merge dictionaries recursively

---

src/fold/base/classes.py
src/fold/composites/select.py
src/fold/models/dummy.py
src/fold/transformations/columns.py
src/fold/transformations/date.py
src/fold/transformations/difference.py
src/fold/transformations/holidays.py
src/fold/transformations/lags.py
src/fold/transformations/math.py
src/fold/transformations/window.py
src/fold/utils/introspection.py

refactor(Base): added default implementation of `get_params()`

---

src/fold/composites/select.py

feature(Optimizer): enable conditional HPO with SelectBest class

---

src/fold/composites/utils.py
tests/unit/test_utils.py

feature(Utils): Clean params now accepts a list of keys with `'passthrough' and '_conditional'` as defaults

---

src/fold/loop/backend/sequential.py
src/fold/loop/backtesting.py

feature(Loop): label tqdm bars

---

.github/workflows/tests.yaml

fix(CI): use the latest `main` branch of krisi

---

tests/unit/test_loop.py

feature(Tests): added tests for score_results()

---

.github/workflows/tests.yaml
pyproject.toml
src/fold/base/classes.py
src/fold/base/scoring.py
src/fold/composites/metalabeling.py
src/fold/composites/residual.py
src/fold/composites/target.py
src/fold/events/__init__.py
src/fold/loop/common.py
src/fold/loop/encase.py
tests/unit/test_loop.py

feature(Events): propagate sample_weights through the Events pipeline

---

src/fold/base/scoring.py
src/fold/models/random.py
tests/unit/test_model.py

feature(Models): added RandomBinaryClassifier that mimicks the distribution of the target

---

src/fold/events/__init__.py
src/fold/events/labeling/__init__.py
src/fold/events/labeling/fixed.py
src/fold/events/utils.py
src/fold/events/weights/__init__.py
tests/integration/test_integration.py
tests/unit/test_artifacts.py
tests/unit/test_events.py
tests/unit/test_loop.py

feature(Events): separate out Labeler and LabelingStrategy

---

src/fold/base/scoring.py
src/fold/events/labeling/fixed.py
src/fold/events/weights/max.py
tests/unit/test_weighing.py

feature(Scoring): use test_sample_weights when result_scoring

---

src/fold/events/__init__.py
src/fold/events/filters/__init__.py
src/fold/events/filters/no.py

feature(Events): added FilterZero class

---

src/fold/events/__init__.py

fix(Events): UsePredefinedEvents should handle sample_weights

---

src/fold/composites/sample.py
src/fold/loop/common.py

fix(Composites): Sample should retain original artifact

---

src/fold/transformations/window.py

feature(Transformation): Updated `AddWindowFeatures` to be consistent between applying `all` and selected columns

---

src/fold/loop/wrap.py
src/fold/transformations/__init__.py
src/fold/transformations/columns.py
src/fold/transformations/function.py
tests/unit/test_transformations.py

feature(Transformation): `ApplyFunction` - apply a function on predefined columns.

---

src/fold/transformations/sklearn.py

feature(Transformation): added `RemoveLowVarianceFeatures` class

---

src/fold/base/classes.py
src/fold/loop/common.py
src/fold/loop/encase.py
src/fold/loop/training.py
src/fold/utils/list.py
tests/integration/test_integration.py

feature(Loop): optionally return in-sample results

---

.gitignore
pyproject.toml
src/fold/composites/__init__.py
src/fold/composites/cache.py
src/fold/composites/columns.py
tests/unit/test_cache.py

feature(Composites): added Cache class

---

src/fold/transformations/function.py

fix(Transformations): ApplyFunction should save past_window_size

---

src/fold/transformations/features.py

feature(Transformation): Expanding window feature with `None == expanding`.

---

src/fold/transformations/difference.py
src/fold/transformations/features.py
src/fold/transformations/function.py
src/fold/utils/dataframe.py

feature(Transformations): replace inf with 0. if fillna=True

---

src/fold/composites/concat.py

feature(Concat): allow custom merge function to be passed in

---

src/fold/composites/utils.py
src/fold/loop/backend/__init__.py
src/fold/loop/backend/pathos.py
src/fold/loop/backend/ray.py
src/fold/loop/backend/sequential.py
src/fold/loop/backend/thread.py
src/fold/loop/backtesting.py
src/fold/loop/training.py

feature(Loop): parallelize backtesting

---

src/fold/composites/imbalance.py
tests/unit/test_composites.py

feature(Composite): `FindThreshold` Composite.

---

src/fold/base/utils.py
src/fold/loop/backend/ray.py
src/fold/loop/backend/sequential.py
src/fold/loop/common.py
src/fold/loop/utils.py
src/fold/loop/wrap.py

fix(Loop): ray backend shouldn't parallelize training of child_transformations

---

src/fold/composites/__init__.py
src/fold/composites/imbalance.py

fix(Composite): Imbalance pipeline export and artifact naming.

---

src/fold/base/classes.py
src/fold/composites/__init__.py
src/fold/composites/concat.py
tests/integration/test_integration.py
tests/unit/test_ensembles.py

fix(Linting): Pipeline (Composite) ranamed to `Sequence` to avoid clash with type `Pipeline` and `Pipelines`.

---

.flake8
docs/api/composites.md
docs/api/models.md
docs/api/transformations.md
src/fold/base/__init__.py
src/fold/base/classes.py
src/fold/composites/__init__.py
src/fold/composites/concat.py
src/fold/composites/select.py
src/fold/models/__init__.py
src/fold/transformations/__init__.py

chore(Types): Exporting all files to get linting and suggestions.

---

src/fold/base/classes.py
src/fold/composites/columns.py
src/fold/composites/imbalance.py
src/fold/composites/metalabeling.py
src/fold/composites/residual.py
src/fold/composites/target.py
src/fold/events/__init__.py
src/fold/loop/common.py
tests/unit/test_composites.py

This still needs to be done for secondary.

feature(Composite): Artifacts are now evaluated after results for Composite primaries.

---

.gitignore
src/fold/base/classes.py
src/fold/composites/cache.py
src/fold/events/labeling/fixed.py
src/fold/loop/checks.py
src/fold/loop/common.py
src/fold/transformations/sklearn.py
tests/unit/test_artifacts.py

feature(Cache): cache per target (now part of Composite.Metadata)

---

src/fold/loop/backend/ray.py

fix(Loop): also free futures when calling ray.internal.free()

---

src/fold/loop/backend/ray.py

feature(Loop): ray should be using shared memory storage again

---

src/fold/transformations/features.py
tests/unit/test_composites.py
tests/unit/test_transformations.py

fix(Transformation): naming output columns of AddWindowFeatures

---

src/fold/composites/columns.py
src/fold/events/__init__.py
src/fold/loop/backtesting.py
src/fold/loop/common.py
src/fold/loop/memory.py
src/fold/loop/process/process_inner_loop.py
src/fold/loop/process/process_minibatch.py
src/fold/transformations/lags.py
src/fold/transformations/math.py
src/fold/utils/dataframe.py

fix(Loop): concat with copy=False everywhere except handling of memory

---

src/fold/transformations/difference.py
tests/unit/test_difference.py

chore(Transformations): removed MakeStationary

---

src/fold/composites/columns.py
src/fold/composites/ensemble.py

refactor(Composites): postprocess_results() renamed to average_results()

---

src/fold/loop/training.py

fix(Training): Path should not default on sequential if there is only one `Fold`.

---

src/fold/base/utils.py
src/fold/loop/common.py

fix(Utils): loop should not return larger artifacts than necessary, _get_maximum_memory_size should not fail on empty pipeline

---

src/fold/events/__init__.py
src/fold/events/base.py
src/fold/events/labeling/fixed.py
src/fold/events/weights/__init__.py
src/fold/events/weights/max.py
src/fold/loop/common.py
src/fold/loop/training.py
tests/integration/test_integration.py
tests/unit/test_artifacts.py
tests/unit/test_cache.py
tests/unit/test_events.py
tests/unit/test_loop.py
tests/unit/test_weighing.py

fix(Loop): UsePredefinedEvents now works as expected

---

src/fold/transformations/sklearn.py

fix(Transformations): `WrapSKLearnFeatureSelector` should return a fully indexed Artifacts

---

src/fold/base/classes.py
src/fold/composites/concat.py
src/fold/loop/common.py
src/fold/loop/training.py
src/fold/loop/utils.py
tests/unit/test_loop.py

refactor(Types): remove old `Transformations` type

---

src/fold/base/classes.py
src/fold/loop/backtesting.py
src/fold/loop/encase.py
src/fold/loop/global.py
src/fold/loop/training.py
tests/unit/test_cache.py
tests/unit/test_composites.py
tests/unit/test_difference.py
tests/unit/test_hpo.py
tests/unit/test_loop.py
tests/unit/test_loop_train_methods.py
tests/unit/test_sklearn.py
tests/unit/test_transformations_datetime.py

feature(Loop): added `PipelineCard` type, optional preprocessing pipeline step

---

README.md
docs/walkthroughs/benchmarking_sktime_fold.ipynb
docs/walkthroughs/benchmarking_sktime_fold.md
docs/walkthroughs/core_walkthrough.ipynb
docs/walkthroughs/core_walkthrough.md
src/fold/models/ar.py
src/fold/models/arima.py
src/fold/models/baseline.py
src/fold/models/garch.py
tests/models/test_ar.py
tests/models/test_arima.py
tests/models/test_baselines.py
tests/models/test_garch.py
tests/models/utils.py

feature(Models): added all models from fold_models package

---

.github/workflows/tests.yaml
src/fold/events/labeling/fixed.py
tests/unit/test_events.py

feature(Events): added `flip_sign` option to `FixedForwardHorizon`

---

src/fold/events/__init__.py
src/fold/loop/common.py
tests/fold/integration/test_integration.py
tests/fold/unit/test_events.py

chore(Events): remove UsePredefinedEvents class

---

src/fold/loop/backend/joblib.py

fix(Loop): Joblib backend

---

src/fold/loop/inference.py
tests/fold/integration/test_integration.py

fix(Inference): extracting the last pipeline correctly

---

tests/fold/integration/test_integration.py

feature(Tests): integration tests for inference

---

src/fold/base/classes.py

fix(Base): Tunable should not inherit from Block

---

src/fold/composites/select.py
src/fold/loop/utils.py

fix(Loop): carry state of Composites when cloning a nested pipeline

---

src/fold/loop/utils.py

fix(Utils): replacing via traversal should work with Clonables

---

src/fold/loop/encase.py
src/fold/loop/training.py

feature(Scoring): Return insample `ScoreCard` from `train_evaluate`

---

src/fold/base/scoring.py
src/fold/composites/optimize.py
src/fold/loop/encase.py
tests/fold/integration/test_integration.py
tests/fold/unit/test_loop.py

feature(Training): Return processed predictions.

---

src/fold/base/utils.py
src/fold/loop/inference.py

feature(Utils): added get_last_trained_pipeline()

---

pyproject.toml
src/fold/transformations/holidays.py
tests/fold/unit/test_transformations_datetime.py

feature(Transformation): Adding holiday features based on exchanges.

---

src/fold/events/labeling/fixed.py
src/fold/utils/forward.py

fix(Labeling): added assertions, logging in failure modes

---

src/fold/base/classes.py
src/fold/composites/cache.py
src/fold/loop/backend/joblib.py
src/fold/loop/backend/pathos.py
src/fold/loop/backend/ray.py
src/fold/loop/backend/sequential.py
src/fold/loop/backend/thread.py
src/fold/loop/common.py
src/fold/loop/training.py
src/fold/loop/updating.py
tests/fold/unit/test_transformations_datetime.py

feature(Loop): added `project_name` to PipelineCard, using it in Cache

---

src/fold/events/labeling/fixed.py
src/fold/events/weights/__init__.py
src/fold/events/weights/max.py

feature(Weighting): simplified code, overridden __str__() in subclasses

---

src/fold/composites/columns.py
src/fold/composites/ensemble.py

feature(Ensemble): added `reconstruct_predictions_from_probabilities`

---

src/fold/utils/checks.py
tests/fold/unit/test_utils.py

fix(Utils): `get_column_names()` should be matching columns correctly

---

src/fold/transformations/dev.py

feature(Transformations): added self.input_columns* to `Test`

---

src/fold/events/labeling/fixed.py

feature(Events): `truncate_if_timeframe_is_smaller` to `FixedForwardHorizon`

---

src/fold/loop/inference.py
src/fold/loop/training.py

fix(Inference): Metadata's name is unified across training/inference

---

src/fold/models/wrappers/gbd.py

feature(Models): omit feature importances in Artifact during `.fit()`
